### ISSUE TITLE
403 errors since Apr 15

### ISSUE THREAD

**Issue by Maje-Ax** [jamesremuscat/pyze#117]
After Apr 15 2024, I have this error with Pyze, 
I tried to change KAMEREON_API_KEY oF09WnKqvBDcrQzcW1rJNpjIuy7KdGaB found in 
https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_fr_FR.json
Without any succes.
Previous working key was YjkKtHmGfaceeuExUDKGxrLZGGvtVS0J
any idea ?

Traceback (most recent call last):
  File "myrenault.py", line 52, in <module>
    accounts = k.get_accounts()
  File "pyze/api/credentials.py", line 29, in inner
    return func(*args, **kwargs)
  File "pyze/api/kamereon.py", line 99, in get_accounts
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/persons/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx?country=FR

**Comment by Maje-Ax** [comment]
Sorry my issue was with mileage not authentication. I messed with login during tests.
But I can't get mileage anymore which made my request failed. Maybe something changed about mileage field.
